nelmio_api_doc:
    documentation:
        info:
            title: Contacts API
            description: An API for fetching, adding, adapting and deleting contacts.
            version: 1.0.0
    areas: # Include everything available at /api except the doc APIs.
        default:
            path_patterns:
                - ^/api(?!/(doc.json|doc)$)
